version: "3"

services:
  database:
    build: "./"
    depends_on:
      - "mongo"
    ports:
      - "3002:3002"

  mongo:
    image: mongo:latest
    command: mongod --port 27017
    ports:
      - "27017:27017"
