USE yelp;

COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/00.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/01.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/02.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/03.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/04.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/05.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/06.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/07.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/08.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/09.csv' WITH HEADER = TRUE;

COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/10.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/11.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/12.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/13.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/14.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/15.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/16.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/17.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/18.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/19.csv' WITH HEADER = TRUE;

COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/20.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/21.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/22.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/23.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/24.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/25.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/26.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/27.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/28.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/29.csv' WITH HEADER = TRUE;

COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/30.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/31.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/32.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/33.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/34.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/35.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/36.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/37.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/38.csv' WITH HEADER = TRUE;
COPY reviews (id, restaurant_id, restaurant_name, username, location, profile_image, count_friends, count_reviews, count_photos, ratings, count_starRatings, post_date, text_review, count_checkin, useful_count, funny_count, cool_count, useful_clicked, funny_clicked, cool_clicked) FROM 'data/39.csv' WITH HEADER = TRUE;
